// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quiyupmtvcsfhnujogug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1aXl1cG10dmNzZmhudWpvZ3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjkzMTgsImV4cCI6MjA2MjI0NTMxOH0.RF6P-2mXoZxCJ_EV8KfYr0TEhi_GyakbCycZIjrOJLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);